macro(set_api_graphics_detection_vars)
  if (API_GRAPHIC STREQUAL "opengl")
    set(api_graphics "opengl")
    add_compile_definitions(API_OPENGL)
  else ()
    set(api_graphics "vulkan")
    add_compile_definitions(API_VULKAN)
  endif ()
endmacro()
